/* All free solid fontawesome icons -> https://fontawesome.com/icons?d=gallery&s=solid&m=free */

import {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faColumns,
    faSearch,
    faTable,
    faTachometerAlt,
    faUser,
    faUsers,
    faUserCircle,
    faPlusCircle,
    faFilter,
    faHome,
    faHouseUser,
    faMoneyCheckAlt,
    faHandshake,
    faLink,
    faUnlink
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeSolidIcons = {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faColumns,
    faSearch,
    faTable,
    faTachometerAlt,
    faUser,
    faUsers,
    faUserCircle,
    faPlusCircle,
    faFilter,
    faHome,
    faHouseUser,
    faMoneyCheckAlt,
    faHandshake,
    faLink,
    faUnlink
};
